global:
  scrape_interval: 5s
scrape_configs:
- job_name: opb
  static_configs:
  - targets: ['localhost:8080','localhost:8082','localhost:8083']
- job_name: recover
  static_configs:
  - targets: ['localhost:9090']
