// Code generated by MockGen. DO NOT EDIT.
// Source: tx.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "github.com/golang/mock/gomock"
)

// MockTxProducer is a mock of TxProducer interface.
type MockTxProducer struct {
	ctrl     *gomock.Controller
	recorder *MockTxProducerMockRecorder
}

// MockTxProducerMockRecorder is the mock recorder for MockTxProducer.
type MockTxProducerMockRecorder struct {
	mock *MockTxProducer
}

// NewMockTxProducer creates a new mock instance.
func NewMockTxProducer(ctrl *gomock.Controller) *MockTxProducer {
	mock := &MockTxProducer{ctrl: ctrl}
	mock.recorder = &MockTxProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxProducer) EXPECT() *MockTxProducerMockRecorder {
	return m.recorder
}

// AbortTransaction mocks base method.
func (m *MockTxProducer) AbortTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTransaction indicates an expected call of AbortTransaction.
func (mr *MockTxProducerMockRecorder) AbortTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTransaction", reflect.TypeOf((*MockTxProducer)(nil).AbortTransaction), ctx)
}

// BeginTransaction mocks base method.
func (m *MockTxProducer) BeginTransaction() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction")
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTxProducerMockRecorder) BeginTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTxProducer)(nil).BeginTransaction))
}

// Close mocks base method.
func (m *MockTxProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTxProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTxProducer)(nil).Close))
}

// CommitTransaction mocks base method.
func (m *MockTxProducer) CommitTransaction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTxProducerMockRecorder) CommitTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTxProducer)(nil).CommitTransaction), ctx)
}

// InitTransactions mocks base method.
func (m *MockTxProducer) InitTransactions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitTransactions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitTransactions indicates an expected call of InitTransactions.
func (mr *MockTxProducerMockRecorder) InitTransactions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitTransactions", reflect.TypeOf((*MockTxProducer)(nil).InitTransactions), ctx)
}

// Produce mocks base method.
func (m *MockTxProducer) Produce(arg0 *kafka.Message, arg1 chan kafka.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockTxProducerMockRecorder) Produce(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockTxProducer)(nil).Produce), arg0, arg1)
}

// SendOffsetsToTransaction mocks base method.
func (m *MockTxProducer) SendOffsetsToTransaction(ctx context.Context, partitions []kafka.TopicPartition, metadata *kafka.ConsumerGroupMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOffsetsToTransaction", ctx, partitions, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOffsetsToTransaction indicates an expected call of SendOffsetsToTransaction.
func (mr *MockTxProducerMockRecorder) SendOffsetsToTransaction(ctx, partitions, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOffsetsToTransaction", reflect.TypeOf((*MockTxProducer)(nil).SendOffsetsToTransaction), ctx, partitions, metadata)
}

// MockConsumerOffsets is a mock of ConsumerOffsets interface.
type MockConsumerOffsets struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerOffsetsMockRecorder
}

// MockConsumerOffsetsMockRecorder is the mock recorder for MockConsumerOffsets.
type MockConsumerOffsetsMockRecorder struct {
	mock *MockConsumerOffsets
}

// NewMockConsumerOffsets creates a new mock instance.
func NewMockConsumerOffsets(ctrl *gomock.Controller) *MockConsumerOffsets {
	mock := &MockConsumerOffsets{ctrl: ctrl}
	mock.recorder = &MockConsumerOffsetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerOffsets) EXPECT() *MockConsumerOffsetsMockRecorder {
	return m.recorder
}

// GetConsumerGroupMetadata mocks base method.
func (m *MockConsumerOffsets) GetConsumerGroupMetadata() (*kafka.ConsumerGroupMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumerGroupMetadata")
	ret0, _ := ret[0].(*kafka.ConsumerGroupMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumerGroupMetadata indicates an expected call of GetConsumerGroupMetadata.
func (mr *MockConsumerOffsetsMockRecorder) GetConsumerGroupMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumerGroupMetadata", reflect.TypeOf((*MockConsumerOffsets)(nil).GetConsumerGroupMetadata))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockTxMetrics is a mock of TxMetrics interface.
type MockTxMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockTxMetricsMockRecorder
}

// MockTxMetricsMockRecorder is the mock recorder for MockTxMetrics.
type MockTxMetricsMockRecorder struct {
	mock *MockTxMetrics
}

// NewMockTxMetrics creates a new mock instance.
func NewMockTxMetrics(ctrl *gomock.Controller) *MockTxMetrics {
	mock := &MockTxMetrics{ctrl: ctrl}
	mock.recorder = &MockTxMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxMetrics) EXPECT() *MockTxMetricsMockRecorder {
	return m.recorder
}

// TxAborted mocks base method.
func (m *MockTxMetrics) TxAborted() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TxAborted")
}

// TxAborted indicates an expected call of TxAborted.
func (mr *MockTxMetricsMockRecorder) TxAborted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxAborted", reflect.TypeOf((*MockTxMetrics)(nil).TxAborted))
}

// TxLatencySec mocks base method.
func (m *MockTxMetrics) TxLatencySec(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TxLatencySec", arg0)
}

// TxLatencySec indicates an expected call of TxLatencySec.
func (mr *MockTxMetricsMockRecorder) TxLatencySec(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxLatencySec", reflect.TypeOf((*MockTxMetrics)(nil).TxLatencySec), arg0)
}

// TxProduced mocks base method.
func (m *MockTxMetrics) TxProduced() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TxProduced")
}

// TxProduced indicates an expected call of TxProduced.
func (mr *MockTxMetricsMockRecorder) TxProduced() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxProduced", reflect.TypeOf((*MockTxMetrics)(nil).TxProduced))
}
